### ISSUE TITLE
[Task] Finish Up GitHub Cog

### ISSUE THREAD

**Issue by No767** [No767/Rin#213]
### Task Description

Need to add the following cmds:

- [x] Get latest release cmd (https://docs.github.com/en/rest/releases/releases#get-the-latest-release)
- [x] List organization repos (https://docs.github.com/en/rest/repos/repos#list-organization-repositories)
- [x] Get a repo (https://docs.github.com/en/rest/repos/repos#get-a-repository)
- [x] List repo lang (https://docs.github.com/en/rest/repos/repos#list-repository-languages)
- [x] List repo contributors (https://docs.github.com/en/rest/repos/repos#list-repository-contributors) (Unable to do so due to max limit) 
- [x] Get repo's readme (https://docs.github.com/en/rest/repos/contents#get-a-repository-readme) (Unable to do so due to max limit) 
- [x] Get repo's readme in a different directory (https://docs.github.com/en/rest/repos/contents#get-a-repository-readme-for-a-directory) (Unable to do so due to max limit) 
- [x] Get a user's info (https://docs.github.com/en/rest/users/users#get-a-user)
